export const STUDY_PROGRAMMES = [
  'COMPUTING',
  'ELECTROTECHNIC',
  'TELECOMMUNICATIONS',
  'SOFTWARE_ENGINEERING',
  'COMPUTING_SCIENCE',
  'COMPUTER_ENGINEERING',
  'INFORMATION_PROCESSING',
  'AUTOMATIZATION',
  'ELECTRONIC_AND_COMPUTER_ENGINEERING',
  'ELECTRONICS',
  'ELECTRICAL_POWER_ENGINEERING',
  'WIRELESS_SYSTEMS'
];
